server:
  port: 8087

spring:
  application:
    name: inventory-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/inventorydb

  mail:
    host: smtp.gmail.com
    port: 587
    username: mahebunnisashaik252@gmail.com
    password: eovrgpinxtaqlxax
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.tracing.OpenTelemetryAutoConfiguration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: b3
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"
  level:
    root: INFO
    com.microservices.inventory: DEBUG

message: "Hello from Config Server for Inventory Service"
